### ISSUE TITLE
調査・検討

### ISSUE THREAD

**Issue by fukuta-tatsuya-intec** [rdbox-intec/rdbox#67]
開発開始時点での方針
- [kubernetes\-dashboard 5\.7\.0 · helm/k8s\-dashboard](https://artifacthub.io/packages/helm/k8s-dashboard/kubernetes-dashboard/5.7.0)のマニフェストをベースとする。
- SSOシーケンス：
  - [Using the OAuth2 filter for SSO \| Edge Stack](https://www.getambassador.io/docs/edge-stack/latest/howtos/oauth-oidc-auth/)を使って`Authorization`ヘッダを追加する。
  - `Authorization`ヘッダを受け取ったk8s-dashboardが、`https://k8s-sso.rdbox~~~~`を経由してKubeAPIサーバーとやり取りする。
    - `https://k8s-sso.rdbox~~~~`：すでにkubectl用に`User impersonation`をサポートしたIngress窓口があるのでそこにトークンを渡してやることで、適切に権限の切り替えが行われる

**Comment by fukuta-tatsuya-intec** [comment]
ec976ea
動作確認を完了した．
大まかな方針としては次の通り．
- AESによるダミーAPIサーバー＋MappingとFilterを使ってImpersonate-\* 用のクライアント証明書を付与
   - /(api|apis)/*の通信時のみクライアント証明書を付与
      - その他は素通り（主に，起動時に/version，/api/v1/namespaces/kubernetes-dashboard/secrets/kubernetes-dashboard-key-holder　と通信する時にサービスアカウント（kubernetes-dashboard）を使ったリクエスト
      - serviceはバグ？パスごとに違う`tls`（クライアント証明書）を提示出来ないっぽいので，わざわざ別々の呼び出しにしている
         - https://kubernetes.default/
         - https://kubernetes.default.svc/
   - FilterPolicy及びTLSContextはクロスNamespace対応
- 通常，k8s-dashboard用のPod→ダミーAPIサーバーはオレオレ証明書エラーになる
   - `--kubeconfig=/original-kubeconfig/values.kubeconfig.yaml`として，証明書及びサービスアカウントのトークンを埋め込んだKube-Configファイルをバインドする．
   - Kube-Configをバインドするために，Service-AccountはHelmを使わずに，別立てで生成する．この時．Appのバージョンに応じてGithubから直接取得するようにする．（Service-Account名は固定）

```bash
kubectl create namespace kubernetes-dashboard

kubectl apply -f values_for_k8s-cert.yaml

kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.6.0/aio/deploy/recommended/05_dashboard-rbac.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.6.0/aio/deploy/recommended/01_dashboard-serviceaccount.yaml

kubectl apply -f values_for_k8s-api-cert.yaml

kubectl apply -f values_for_k8s-api-ingress.yaml

sleep 40

bash values_gen.bash

kubectl -n kubernetes-dashboard create cm kubeconfig --from-file values.kubeconfig.yaml

helm -n kubernetes-dashboard upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --create-namespace -f values_for_k8s-dashboard.yaml

kubectl -n kubernetes-dashboard apply -f values_for_k8s-ingress.yaml

## Keycloakでクライアントを作成 ##

kubectl -n kubernetes-dashboard apply -f values_for_k8s-filter.yaml
```

values_for_k8s-cert.yaml
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-issuer-ca.kubernetes-dashboard.rdbox.*.nip.io
  namespace: kubernetes-dashboard
  labels:
    app.kubernetes.io/name: template-engine
    app.kubernetes.io/instance: kubernetes-dashboard
    app.kubernetes.io/component: dependency-injection
    app.kubernetes.io/part-of: datawire.edge-stack
    app.kubernetes.io/managed-by: rdbox
    rdbox.local/format: v1beta1
    rdbox.local/chart: 0.1.0
spec:
  isCA: true
  commonName: "kubernetes-dashboard.rdbox.*.nip.io"
  dnsNames:
    - kubernetes-dashboard.rdbox.*.nip.io
    - "*.kubernetes-dashboard.rdbox.*.nip.io"
  secretName: kubernetes-dashboard.rdbox.*.nip.io
  duration: 8760h
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: cluster-issuer-ca.rdbox.*.nip.io
    kind: ClusterIssuer
    group: cert-manager.io
```

values_for_k8s-api-cert.yaml
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-issuer-ca.apiserver-kubernetes-dashboard.rdbox.*.nip.io
  namespace: kubernetes-dashboard
  labels:
    app.kubernetes.io/name: template-engine
    app.kubernetes.io/instance: kubernetes-dashboard
    app.kubernetes.io/component: dependency-injection
    app.kubernetes.io/part-of: datawire.edge-stack
    app.kubernetes.io/managed-by: rdbox
    rdbox.local/format: v1beta1
    rdbox.local/chart: 0.1.0
spec:
  isCA: true
  commonName: "apiserver-kubernetes-dashboard.rdbox.*.nip.io"
  dnsNames:
    - apiserver-kubernetes-dashboard.rdbox.*.nip.io
    - "*.apiserver-kubernetes-dashboard.rdbox.*.nip.io"
  secretName: apiserver-kubernetes-dashboard.rdbox.*.nip.io
  duration: 8760h
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: cluster-issuer-ca.rdbox.*.nip.io
    kind: ClusterIssuer
    group: cert-manager.io
```

values_for_k8s-api-ingress.yaml
```yaml
---
# Source: template-engine/templates/ambassador/manifests/endpoint/host.yaml
##
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: apiserver-kubernetes-dashboard
  namespace: kubernetes-dashboard
  labels:
    app.kubernetes.io/name: template-engine
    app.kubernetes.io/instance: kubernetes-dashboard
    app.kubernetes.io/component: dependency-injection
    app.kubernetes.io/part-of: datawire.edge-stack
    app.kubernetes.io/managed-by: rdbox
    rdbox.local/format: v1beta1
    rdbox.local/chart: 0.1.0
spec:
  hostname: apiserver-kubernetes-dashboard.rdbox.*.nip.io
  requestPolicy:
    insecure:
      action: Route
  tlsSecret:
    name: apiserver-kubernetes-dashboard.rdbox.*.nip.io
---
# Source: fallback.yaml
##
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: hd-apiserver-kubernetes-dashboard
  namespace: kubernetes-dashboard
  labels:
    app.kubernetes.io/name: template-engine
    app.kubernetes.io/instance: kubernetes-dashboard
    app.kubernetes.io/component: dependency-injection
    app.kubernetes.io/part-of: datawire.edge-stack
    app.kubernetes.io/managed-by: rdbox
    rdbox.local/format: v1beta1
    rdbox.local/chart: 0.1.0
spec:
  host: apiserver-kubernetes-dashboard.rdbox.*.nip.io
  prefix: /api/v1/namespaces/kubernetes-dashboard/secrets/kubernetes-dashboard-key-holder
  rewrite: ""
  allow_upgrade:
  - spdy/3.1
  service: https://kubernetes.default.svc/
  timeout_ms: 0
---
# Source: fallback.yaml
##
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: api-apiserver-kubernetes-dashboard
  namespace: kubernetes-dashboard
  labels:
    app.kubernetes.io/name: template-engine
    app.kubernetes.io/instance: kubernetes-dashboard
    app.kubernetes.io/component: dependency-injection
    app.kubernetes.io/part-of: datawire.edge-stack
    app.kubernetes.io/managed-by: rdbox
    rdbox.local/format: v1beta1
    rdbox.local/chart: 0.1.0
spec:
  host: apiserver-kubernetes-dashboard.rdbox.*.nip.io
  prefix: "/(api|apis)/.*"
  prefix_regex: true
  rewrite: ""
  allow_upgrade:
  - spdy/3.1
  service:  https://kubernetes.default/
  timeout_ms: 0
  tls: kubernetes-dashboard-k8ssso
---
# Source: fallback.yaml
##
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: api2-apiserver-kubernetes-dashboard
  namespace: kubernetes-dashboard
  labels:
    app.kubernetes.io/name: template-engine
    app.kubernetes.io/instance: kubernetes-dashboard
    app.kubernetes.io/component: dependency-injection
    app.kubernetes.io/part-of: datawire.edge-stack
    app.kubernetes.io/managed-by: rdbox
    rdbox.local/format: v1beta1
    rdbox.local/chart: 0.1.0
spec:
  host: apiserver-kubernetes-dashboard.rdbox.*.nip.io
  prefix: "/(api|apis)"
  prefix_regex: true
  rewrite: ""
  allow_upgrade:
  - spdy/3.1
  service:  https://kubernetes.default/
  timeout_ms: 0
  tls: kubernetes-dashboard-k8ssso
---
# Source: fallback.yaml
##
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: fb-apiserver-kubernetes-dashboard
  namespace: kubernetes-dashboard
  labels:
    app.kubernetes.io/name: template-engine
    app.kubernetes.io/instance: kubernetes-dashboard
    app.kubernetes.io/component: dependency-injection
    app.kubernetes.io/part-of: datawire.edge-stack
    app.kubernetes.io/managed-by: rdbox
    rdbox.local/format: v1beta1
    rdbox.local/chart: 0.1.0
spec:
  host: apiserver-kubernetes-dashboard.rdbox.*.nip.io
  prefix: /
  rewrite: ""
  allow_upgrade:
  - spdy/3.1
  service: https://kubernetes.default.svc/
  timeout_ms: 0
---
apiVersion: getambassador.io/v3alpha1
kind: FilterPolicy
metadata:
  name: apiserver-kubernetes-dashboard
  namespace: kubernetes-dashboard
  labels:
    app.kubernetes.io/name: template-engine
    app.kubernetes.io/instance: kubernetes-dashboard
    app.kubernetes.io/component: dependency-injection
    app.kubernetes.io/part-of: datawire.edge-stack
    app.kubernetes.io/managed-by: rdbox
    rdbox.local/format: v1beta1
    rdbox.local/chart: 0.1.0
spec:
  rules:
  - host: apiserver-kubernetes-dashboard.rdbox.*.nip.io
    path: /api/v1/namespaces/kubernetes-dashboard/secrets/kubernetes-dashboard-key-holder
    filters: null
  - host: apiserver-kubernetes-dashboard.rdbox.*.nip.io
    path: "/api/*"
    filters:
    - name: ambassador-k8ssso
      namespace: ambassador
  - host: apiserver-kubernetes-dashboard.rdbox.*.nip.io
    path: "/apis/*"
    filters:
    - name: ambassador-k8ssso
      namespace: ambassador
  - host: apiserver-kubernetes-dashboard.rdbox.*.nip.io
    path: "/api"
    filters:
    - name: ambassador-k8ssso
      namespace: ambassador
  - host: apiserver-kubernetes-dashboard.rdbox.*.nip.io
    path: "*"
    filters: null
---
apiVersion: getambassador.io/v3alpha1
kind: TLSContext
metadata:
  name: kubernetes-dashboard-k8ssso
  namespace: kubernetes-dashboard
  labels:
    app.kubernetes.io/name: template-engine
    app.kubernetes.io/instance: ambassador-k8ssso
    app.kubernetes.io/component: dependency-injection
    app.kubernetes.io/part-of: datawire.edge-stack
    app.kubernetes.io/managed-by: rdbox
    rdbox.local/format: v1beta1
    rdbox.local/chart: 0.1.0
spec:
  hosts:
  - apiserver-kubernetes-dashboard.rdbox.*.nip.io
  secret: ambassador-k8ssso.ambassador
```

values_gen.bash
```bash
#!/usr/bin/env bash
set -euox pipefail

namespace=kubernetes-dashboard

# your server name goes here
server=https://apiserver-kubernetes-dashboard.rdbox.*.nip.io
# the name of the secret containing the service account token goes here
name=$(kubectl -n kubernetes-dashboard get secrets -o name | grep "kubernetes-dashboard-token")

ca=$(kubectl -n cert-manager get secret rdbox.*.nip.io -o jsonpath='{.data.tls\.crt}')
token=$(kubectl -n $namespace get $name -o jsonpath='{.data.token}' | base64 --decode)

echo "
apiVersion: v1
kind: Config
clusters:
- name: default-cluster
  cluster:
    certificate-authority-data: ${ca}
    server: ${server}
contexts:
- name: default-context
  context:
    cluster: default-cluster
    namespace: ${namespace}
    user: default-user
current-context: default-context
users:
- name: default-user
  user:
    token: ${token}
" > values.kubeconfig.yaml
```

values_for_k8s-dashboard.yaml
```yaml
extraArgs:
  - --apiserver-host=https://apiserver-kubernetes-dashboard.rdbox.*.nip.io
  - --tls-cert-file=/original-certs/tls.crt
  - --tls-key-file=/original-certs/tls.key
  - --kubeconfig=/original-kubeconfig/values.kubeconfig.yaml
protocolHttp: false
extraVolumeMounts:
  - name: tls-dashboard
    mountPath: "/original-certs"
    readOnly: true
  - name: kubeconfig
    mountPath: "/original-kubeconfig"
extraVolumes:
  - name: tls-dashboard
    secret:
      secretName: kubernetes-dashboard.rdbox.*.nip.io
  - name: kubeconfig
    configMap:
      name: kubeconfig
rbac:
  create: false
serviceAccount:
  create: false
  name: kubernetes-dashboard
metricsScraper:
  enabled: true
metrics-server:
  enabled: true
  args:
    - --kubelet-insecure-tls
```

values_for_k8s-ingress.yaml
```yaml
---
# Source: template-engine/templates/ambassador/manifests/endpoint/tls-context.yaml
##
apiVersion: getambassador.io/v3alpha1
kind: TLSContext
metadata:
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
  labels:
    app.kubernetes.io/name: template-engine
    app.kubernetes.io/instance: kubernetes-dashboard
    app.kubernetes.io/component: dependency-injection
    app.kubernetes.io/part-of: datawire.edge-stack
    app.kubernetes.io/managed-by: rdbox
    rdbox.local/format: v1beta1
    rdbox.local/chart: 0.1.0
spec:
  hosts:
  - kubernetes-dashboard.rdbox.*.nip.io
  secret: kubernetes-dashboard.rdbox.*.nip.io
---
# Source: template-engine/templates/ambassador/manifests/endpoint/host.yaml
##
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
  labels:
    app.kubernetes.io/name: template-engine
    app.kubernetes.io/instance: kubernetes-dashboard
    app.kubernetes.io/component: dependency-injection
    app.kubernetes.io/part-of: datawire.edge-stack
    app.kubernetes.io/managed-by: rdbox
    rdbox.local/format: v1beta1
    rdbox.local/chart: 0.1.0
spec:
  hostname: kubernetes-dashboard.rdbox.*.nip.io
  requestPolicy:
    insecure:
      action: Route
  tlsSecret:
    name: kubernetes-dashboard.rdbox.*.nip.io
---
# Source: template-engine/templates/ambassador/manifests/endpoint/mapping.yaml
##
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
  labels:
    app.kubernetes.io/name: template-engine
    app.kubernetes.io/instance: kubernetes-dashboard
    app.kubernetes.io/component: dependency-injection
    app.kubernetes.io/part-of: datawire.edge-stack
    app.kubernetes.io/managed-by: rdbox
    rdbox.local/format: v1beta1
    rdbox.local/chart: 0.1.0
spec:
  host: kubernetes-dashboard.rdbox.*.nip.io
  prefix: /
  allow_upgrade:
  - spdy/3.1
  service: kubernetes-dashboard.kubernetes-dashboard:443
  timeout_ms: 0
  tls: kubernetes-dashboard
```

values_for_k8s-filter.yaml
```yaml
# Source: template-engine/templates/kubernetes-dashboard/manifests/filter/filter-policy.yaml
##
apiVersion: getambassador.io/v3alpha1
kind: FilterPolicy
metadata:
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
  labels:
    app.kubernetes.io/name: template-engine
    app.kubernetes.io/instance: kubernetes-dashboard
    app.kubernetes.io/component: dependency-injection
    app.kubernetes.io/part-of: datawire.edge-stack
    app.kubernetes.io/managed-by: rdbox
    rdbox.local/format: v1beta1
    rdbox.local/chart: 0.1.0
spec:
  rules:
  - host: kubernetes-dashboard.rdbox.*.nip.io
    path: "*"
    filters:
    - name: kubernetes-dashboard
---
# Source: template-engine/templates/kubernetes-dashboard/manifests/filter/filter.yaml
##
apiVersion: getambassador.io/v3alpha1
kind: Filter
metadata:
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
  labels:
    app.kubernetes.io/name: template-engine
    app.kubernetes.io/instance: kubernetes-dashboard
    app.kubernetes.io/component: dependency-injection
    app.kubernetes.io/part-of: datawire.edge-stack
    app.kubernetes.io/managed-by: rdbox
    rdbox.local/format: v1beta1
    rdbox.local/chart: 0.1.0
spec:
  OAuth2:
    authorizationURL: https://keycloak.rdbox.*.nip.io/realms/rdbox
    clientID: kubernetes-dashboard ## OAuth2 client from your IdP
    secret: rsa80HO8woYfeGg8ktURRVrG7io2moCY ## Secret used to access OAuth2 client
    protectedOrigins:
    - origin: https://kubernetes-dashboard.rdbox.*.nip.io/.ambassador/oauth2/redirection-endpoint

```
