### ISSUE TITLE
UPD MetalLB_v0.13

### ISSUE THREAD

**Issue by fukuta-tatsuya-intec** [rdbox-intec/rdbox#74]
L2Addressの指定方法が変更となっている
[MetalLB, bare metal load\-balancer for Kubernetes](https://metallb.universe.tf/#backward-compatibility)

[Layer 2 Configuration](https://metallb.universe.tf/configuration/#layer-2-configuration)
こんな感じでCRDが新しく定義されたのでそれを使う．
```yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.240-192.168.1.250
```
