### ISSUE TITLE
新規モジュール追加用スニペット

### ISSUE THREAD

**Issue by fukuta-tatsuya-intec** [rdbox-intec/rdbox#90]
# 新規モジュール追加用スニペット
```bash
bash dev.module.add.bash aes-admin v1beta1
```

1. モジュール名
2. バージョン（テンプレートバージョン）

次が自動生成される
- Create files/dirs
  - main-script
  - conf
  - template-engine
    - dynamics/values.yamlは雛形も自動生成する

## 雛形のサンプル
ちゃんとモジュール名がキャメルケースになっていることに注目
  ```yaml
  ##
  {{- if .Values.aesAdmin }}
  {{- if and .Values.global.dynamics (hasKey .Values.global "dynamics")}}
  aesAdmin:
    dynamics:
      common:
        baseFqdn: {{ .Values.aesAdmin.dynamics.common.baseFqdn }}
      main:
        hostname: {{ .Values.aesAdmin.dynamics.main.hostname }}
  {{- end }}
  {{- end }}
  ```
