### ISSUE TITLE
リファクタリング（CD部）

### ISSUE THREAD

**Issue by fukuta-tatsuya-intec** [rdbox-intec/rdbox#93]

**Comment by fukuta-tatsuya-intec** [comment]
helm descriptionsはこんな感じで呼び出せる．
```bash
$ helm -n cert-manager history cert-manager -o yaml
```

```yaml
- app_version: v1.9.1
  chart: cert-manager-v1.9.1
  description: CREATES_RELEASE_ID=r1660111713205
  revision: 10
  status: deployed
  updated: "2022-08-10T06:08:37.299286375Z"
```
