### ISSUE TITLE
Create部を作成する

### ISSUE THREAD

**Issue by fukuta-tatsuya-intec** [rdbox-intec/rdbox#94]
Ambassadorのデバッグツールである「Ambassador Diagnostic Overview」に対しての外部アクセスポイントを提供する．
- [URLの例（https://ambassador-admin.rdbox.172-16-0-110.nip.io/ambassador/v0/diag/）](https://ambassador-admin.rdbox.172-16-0-110.nip.io/ambassador/v0/diag/)
- 所属グループが「cluster-admin」のユーザのみがアクセス可能であること

![image](https://user-images.githubusercontent.com/40556102/185059984-8ba7c2c6-575c-44ab-a935-cf4a7435af3b.png)

**Comment by fukuta-tatsuya-intec** [comment]
FilterPolicyを使い分けることで擬似的にRBACを実現している．

1. -oauth2フィルタでJWTを取得
2. 取得したJWTを-jwt-impersonateフィルタで分解，グループをヘッダーにセット
3. ヘッダーを元に処理（-jwt-dummyフィルタという何もしないフィルタを適用）
  - 「Impersonate-Group=cluster-admin」の時は「onAllow: "break"」
    - リクエストに修正を加え、フィルター処理を終了し、修正後のリクエストを上流サービスへ転送する。それ以降のフィルターは呼び出されない。
    - https://www.getambassador.io/docs/edge-stack/latest/topics/using/filters/#managing-filters
  - 「Impersonate-Group」ヘッダーはあるがそれ以外の時は「onDeny: "break"」
    - フィルターが「HTTP レスポンス」を返したとき：処理を終了し、要求元のHTTPクライアントに直接レスポンスを返します。後のフィルタは呼ばれない。リクエストは上流のサービスには転送されない。
    - 「フィルターが「HTTP レスポンス」を返したとき：」を引き起こすため，.arguments.scope[]="deny"を指定することでわざとエラーを引き起こす．
    - `あるパスのスコープ値のいずれかが許可されていない場合、そのリソースへのアクセスは禁止されます。もし scope 引数に foo を指定しても、プロバイダからの認証応答に foo が含まれていなければ、認証済みユーザが foo というリソーススコープを持っていないので、認証サーバがこのパスへのアクセスを禁止したものと見なされます。`
    - https://www.getambassador.io/docs/edge-stack/latest/topics/using/filters/oauth2/#oauth2-path-specific-arguments

```yaml
apiVersion: getambassador.io/v3alpha1
kind: FilterPolicy
metadata:
  name: "{{ .Values.ambassadorAdmin.dynamics.main.hostname }}"
  namespace: {{ template "common.names.namespace" . }}
  labels: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: dependency-injection
    app.kubernetes.io/part-of: datawire.edge-stack
    app.kubernetes.io/managed-by: rdbox
    rdbox.local/format: v1beta1
    rdbox.local/chart: {{ .Chart.Version }}
spec:
  rules:
  - host: "{{ .Values.ambassadorAdmin.dynamics.main.fqdn }}"
    path: "*"
    filters:
    - name: "{{ .Values.ambassadorAdmin.dynamics.main.hostname }}-oauth2"
    - name: "{{ .Values.ambassadorAdmin.dynamics.main.hostname }}-jwt-impersonate"
    - name: "{{ .Values.ambassadorAdmin.dynamics.main.hostname }}-jwt-dummy"
      ifRequestHeader:
        name: "Impersonate-Group"
        value: "cluster-admin"
      onAllow: "break"
    - name: "{{ .Values.ambassadorAdmin.dynamics.main.hostname }}-jwt-dummy"
      ifRequestHeader:
        name: "Impersonate-Group"
      onDeny: "break"
      arguments:
        scope:
          - "deny"
```
